export const REQUEST_ADDRESS_PENDING = 'REQUEST_ADDRESS_PENDING';
export const REQUEST_ADDRESS_SUCCESS = 'REQUEST_ADDRESS_SUCCESS';
export const REQUEST_ADDRESS_FAILED = 'REQUEST_ADDRESS_FAILED';
export const BASE_API_URL = 'http://localhost:3000/phones.json';